### ISSUE TITLE
Action breaks with ubuntu-20.04

### ISSUE THREAD

**Issue by maelvls** [actions-ml/setup-ocaml#5]
Hi!

Thank you so much for your work on this github action!! ✨

I tested your action with ubuntu-20.04; the reason why I use ubuntu-20.04 instead of ubuntu-latest is that Github will soon change ubuntu-latest fron 18.04 bionic to 20.04 focal:

> Ubuntu-latest workflows will use Ubuntu-20.04 soon. For more details, see https://github.com/actions/virtual-environments/issues/1816.

The `actions-ml/setup-ocaml` action currently relies on @avsm's ppa, which, as of today, only contains [a bionic port](http://ppa.launchpad.net/avsm/musl/ubuntu/dists/), not a focal one. For example, in [1], the action log shows:

    Get:56 http://ppa.launchpad.net/avsm/musl/ubuntu bionic/main amd64 Packages [808 B]

Do you have an idea on how to get around this limitation? Right now, my workaround is to [use ubuntu-latest](https://github.com/maelvls/ocamlyices2/commit/6f94b881) 👍

Thank you!

[1]: https://github.com/actions-ml/setup-ocaml/runs/1641341003

**Comment by smorimoto** [comment]
Yes, I'm aware of the problem and have specs to fix it. (But note that the current version is still a result of dumping my ideas.)

**Comment by smorimoto** [comment]
If I have enough time today, I can fix it today. By the way, I don't really want to recommend using `actions/cache`. In many cases it's not very robust to use and should be avoided, especially for OCaml projects. Also, thrashing can easily occur due to the cache limit.

**Comment by smorimoto** [comment]
I sent a patch to `actions/cache` to use zstd for the OCaml projects a year ago, but now limit is the primary issue... That's one of the reasons I started this project.

**Comment by maelvls** [comment]
> I don't really want to recommend using actions/cache. In many cases, it's not very robust to use and should be avoided, especially for OCaml projects

Thanks for the advice, I'll remove the caching of ~/.opam then 👍

Would be probably worth mentioning this in the README 😁

**Comment by smorimoto** [comment]
Yes, indeed. The README is fairly sloppy and needs to be completely rewritten...

**Comment by smorimoto** [comment]
I have just pushed a quick patches. That must work as expected.
