### ISSUE TITLE
[wish] Support OPAM files requiring custom repos

### ISSUE THREAD

**Issue by na4zagin3** [actions-ml/setup-ocaml#7]
Hi!

I'm trying to use this Action for https://github.com/na4zagin3/satyrographos-repo and so on https://github.com/na4zagin3/satysfi-fss but it doesn't work well (https://github.com/na4zagin3/satyrographos-repo/pull/309) because `*.opam` files at the project root depends on packages at multiple custom OPAM repos in addition to the OPAM official repo.

As far as I understand, this doesn't support custom OPAM repos yet.  If so, can it have another input parameter, for example, CUSTOM_REPOSITORIES or OVERLAY_REPOSITORIES, that takes a comma-separated list of `<repo-name>=<repo-url>` like [`--repos=` option of `opam switch create` subcommand](https://opam.ocaml.org/doc/Manual.html#Repositories)?

**Comment by smorimoto** [comment]
actions-ml project is already deprecated. I will transfer this to the avsm repository.

**Comment by na4zagin3** [comment]
Okay. I'll try it with avsm’s v2 or master and file a request there.  Thanks!
